before_script:
    - docker build -t blackbox-ionic-build-env ./docker-build-env

release:
    script:
        - mkdir -p /tmp/BlackBox-ionic-tmp

        # Cache cordova plugins in tmp
        - grep 'cordova_plugin_add_git ' init.sh |
            sed -r 's/[^ ]+ (.*)/\1/' |
            xargs -n1 -I '{}'
                sh -c 'git clone --depth=1 "{}" /tmp/BlackBox-ionic-tmp/$(basename "{}")'
            || true

        # Build
        - docker run
            --rm
            --volume "$(pwd):/mnt/BlackBox-ionic"
            --volume "/tmp/BlackBox-ionic-tmp:/tmp"
            --workdir "/mnt/BlackBox-ionic"
            --user "$(id -u)"
            --env "HOME=/tmp"
            --env "GRADLE_USER_HOME=/tmp/gradle"
            blackbox-ionic-build-env
            sh -c "bash init.sh && ionic browser add crosswalk && ionic build android"

        # Deploy
        - SHARE_ROOT=/www/share/BlackBox-ionic_d283a397ed9973eb770fd6ca61f680e49c
        - CURRENT_SHARE_ROOT=$SHARE_ROOT/`date +%F_%R`

        - mkdir $CURRENT_SHARE_ROOT
        - cp ./platforms/android/build/outputs/apk/android-armv7-debug.apk $CURRENT_SHARE_ROOT

        # Remove old builds (older than 10 builds ago)
        - cd $SHARE_ROOT && rm -rf `ls | head -n 10`
    type: deploy
    tags: 
    except:
        - tags
